// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAenuoU6NdfSvbUgZti_OjCVhK45GKckuY',
    appId: '1:483811394988:web:d6bbb86a2d0d50c61f2609',
    messagingSenderId: '483811394988',
    projectId: 'efootballersbd',
    authDomain: 'efootballersbd.firebaseapp.com',
    storageBucket: 'efootballersbd.firebasestorage.app',
    measurementId: 'G-NBBNPCVKLM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwvCelo2XHb7hZBeqbwU0lwEj_oFOFJ7A',
    appId: '1:483811394988:android:edd9b45a8a7a9fd71f2609',
    messagingSenderId: '483811394988',
    projectId: 'efootballersbd',
    storageBucket: 'efootballersbd.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNJdB_bNtCvKOww0l6X2omI610jCQ0IBE',
    appId: '1:483811394988:ios:8069679668ae37a31f2609',
    messagingSenderId: '483811394988',
    projectId: 'efootballersbd',
    storageBucket: 'efootballersbd.firebasestorage.app',
    iosBundleId: 'com.example.efbd',
  );
}
